/** Serializable defaults for Settings → Notifications (no React icons). */

export const DEFAULT_NOTIFICATION_CHANNELS = [
  {
    id: "email",
    name: "Email Notifications",
    type: "email",
    enabled: true,
    description: "Send notifications via email to users",
  },
  {
    id: "push",
    name: "Push Notifications",
    type: "push",
    enabled: true,
    description: "Browser and mobile push notifications",
  },
  {
    id: "sms",
    name: "SMS Notifications",
    type: "sms",
    enabled: false,
    description: "Text message notifications for urgent alerts",
  },
  {
    id: "in_app",
    name: "In-App Notifications",
    type: "in_app",
    enabled: true,
    description: "Notifications within the application",
  },
] as const;

export const DEFAULT_NOTIFICATION_TYPES = [
  {
    id: "event_reminder",
    name: "Event Reminder",
    description: "Remind users about upcoming events",
    category: "Events",
    channels: { email: true, push: true, sms: false, inApp: true },
    priority: "high",
    userConfigurable: true,
  },
  {
    id: "registration_confirmation",
    name: "Registration Confirmation",
    description: "Confirm event registration to users",
    category: "Events",
    channels: { email: true, push: true, sms: false, inApp: true },
    priority: "high",
    userConfigurable: false,
  },
  {
    id: "payment_confirmation",
    name: "Payment Confirmation",
    description: "Confirm successful payments",
    category: "Payments",
    channels: { email: true, push: true, sms: true, inApp: true },
    priority: "high",
    userConfigurable: false,
  },
  {
    id: "message_received",
    name: "New Message",
    description: "Notify users of new messages",
    category: "Communication",
    channels: { email: true, push: true, sms: false, inApp: true },
    priority: "normal",
    userConfigurable: true,
  },
  {
    id: "booking_confirmation",
    name: "Booking Confirmation",
    description: "Confirm venue or appointment bookings",
    category: "Bookings",
    channels: { email: true, push: true, sms: false, inApp: true },
    priority: "high",
    userConfigurable: false,
  },
  {
    id: "system_update",
    name: "System Update",
    description: "Important system announcements",
    category: "System",
    channels: { email: true, push: false, sms: false, inApp: true },
    priority: "normal",
    userConfigurable: true,
  },
  {
    id: "connection_request",
    name: "Connection Request",
    description: "New connection requests from users",
    category: "Social",
    channels: { email: true, push: true, sms: false, inApp: true },
    priority: "normal",
    userConfigurable: true,
  },
  {
    id: "appointment_reminder",
    name: "Appointment Reminder",
    description: "Remind users about upcoming appointments",
    category: "Appointments",
    channels: { email: true, push: true, sms: true, inApp: true },
    priority: "high",
    userConfigurable: true,
  },
];

export const DEFAULT_NOTIFICATION_SCHEDULES = [
  {
    id: "1",
    name: "Daily Digest",
    type: "digest",
    frequency: "daily",
    time: "09:00",
    timezone: "UTC",
    enabled: true,
    lastRun: "2024-01-15T09:00:00Z",
    nextRun: "2024-01-16T09:00:00Z",
  },
  {
    id: "2",
    name: "Event Reminders",
    type: "reminder",
    frequency: "hourly",
    time: "00:00",
    timezone: "UTC",
    enabled: true,
    lastRun: "2024-01-15T14:00:00Z",
    nextRun: "2024-01-15T15:00:00Z",
  },
  {
    id: "3",
    name: "Weekly Summary",
    type: "summary",
    frequency: "weekly",
    time: "10:00",
    timezone: "UTC",
    enabled: true,
    lastRun: "2024-01-08T10:00:00Z",
    nextRun: "2024-01-15T10:00:00Z",
  },
];

export const DEFAULT_NOTIFICATION_GLOBAL_SETTINGS = {
  quietHoursEnabled: true,
  quietHoursStart: "22:00",
  quietHoursEnd: "08:00",
  batchNotifications: true,
  batchInterval: 15,
  maxNotificationsPerHour: 10,
  respectUserPreferences: true,
  defaultPriority: "normal",
  retryFailedAttempts: 3,
  retryDelayMinutes: 5,
};
